module.exports = {
  ".html": "text/html; charset=utf-8",
  ".htm": "text/html; charset=utf-8",
  ".xhtml": "application/xhtml+xml; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".xml": "text/xml; charset=utf-8",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".collection": "font/collection",
  ".otf": "font/otf",
  ".sfnt": "font/sfnt",
  ".ttf": "font/ttf",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".json": "application/json",
  ".mp3": "audio/mpeg",
  ".oga": "audio/ogg",
  ".ogg": "application/ogg",
  ".ogv": "video/ogg",
  ".mp4": "video/mp4",
  ".mpeg": "video/mpeg",
  ".mpg": "video/mpeg",
  ".avi": "video/avi",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".wav": "audio/wav",
  ".wasm": "application/wasm",
  ".atom": "application/atom+xml",
  ".rss": "application/rss+xml",
  ".mml": "text/mathml",
  ".txt": "text/plain",
  ".jad": "text/vnd.sun.j2me.app-descriptor",
  ".wml": "text/vnd.wap.wml",
  ".htc": "text/x-component",
  ".zip": "application/zip",
  ".pdf": "application/pdf",
  ".yml": "text/yaml",
  ".md": "text/plain",
  ".vtt": "text/vtt"
};